when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'

framework:
    messenger:
        failure_transport: failed

        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\ChainMiddleware

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 0
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: async
            Symfony\Component\Notifier\Message\ChatMessage: async
            Symfony\Component\Notifier\Message\SmsMessage: async
            App\Message\ProcessPodcast: async
            App\Message\OptimizePodcast: async
            App\Message\ReleasePodcast: async
            Opis\Closure\SerializableClosure: async

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
